description: Driver resource
get:
  description: Get all drivers
  responses:
    200:
      body:
        application/json:
          example: (soon)

/{driverId}:
  get:
    description: Get one driver
    responses:
      200:
        body:
          application/json:
            example: (soon)
      404:
        description: The resource was not found.
