#%RAML 0.8
---
title: Symbiot API
baseUri: https://localhost:8080
version: v1
protocols: [HTTPS]
mediaType: application/json

traits:
  - private: !include _traits/private.raml

/inputs: !include inputs/inputs.raml
/outputs: !include outputs/outputs.raml
/streams: !include streams/streams.raml
/drivers: !include drivers/drivers.raml
